; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.42"

; Modules
projects[captcha_pack][version] = "1.0-alpha1"

projects[ctools][version] = "1.9"

projects[captcha][version] = "1.3"

projects[colorbox][version] = "2.10"

projects[context][version] = "3.6"

projects[ds][version] = "2.13"

projects[ds_bootstrap_layouts][version] = "3.1"

projects[eck][version] = "2.0-rc8"

projects[entity][version] = "1.6"

projects[entityreference][version] = "1.1"

projects[field_collection][version] = "1.0-beta11"

projects[field_formatter_settings][version] = "1.1"

projects[google_analytics][version] = "2.1"

projects[honeypot][version] = "1.21"

projects[imce][version] = "1.9"

projects[insert][version] = "1.3"

projects[intlinks][version] = "1.3"

projects[jquery_update][version] = "2.7"

projects[libraries][version] = "2.2"

projects[link][version] = "1.4"

projects[markdown][version] = "1.2"

projects[migrate][version] = "2.8"

projects[migrate_extras][version] = "2.5"

projects[module_filter][version] = "2.0"

projects[mollom][version] = "2.15"

projects[path_breadcrumbs][version] = "3.3"

projects[pathauto][version] = "1.3"

projects[private][version] = "1.2"

projects[redirect][version] = "1.0-rc3"

projects[rules][version] = "2.9"

projects[select_or_other][version] = "2.22"

projects[smtp][version] = "1.3"

projects[textformatter][version] = "1.4"

projects[token][version] = "1.6"

projects[token_filter][version] = "1.1"

projects[views][version] = "3.13"

projects[webform][version] = "4.12"

projects[wordpress_migrate][version] = "2.3"

projects[youtube][version] = "1.6"

; Themes
projects[adminimal_theme][version] = "1.17"

projects[bootstrap][version] = "3.4"

projects[ember][version] = "2.0-alpha4"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[full_stack][download][type] = ""
projects[full_stack][download][url] = ""
projects[full_stack][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[syntaxhighlighter_3.0.83][download][type] = ""
libraries[syntaxhighlighter_3.0.83][download][url] = ""
libraries[syntaxhighlighter_3.0.83][directory_name] = "syntaxhighlighter_3.0.83"
libraries[syntaxhighlighter_3.0.83][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

